### ISSUE TITLE
Phantomjs: Permission denied

### ISSUE THREAD

**Issue by ak-notify** [tauksun/html-pdf-phantomBinIncluded#1]
While running 
`pdf.create(html, options).toFile(outputFile, callback)`

Getting error:
```
Error: html-pdf: Unknown Error
sh: /node_modules/html-pdf-phantomjs-included/phantom-binary/phantomjs: Permission denied

    at ChildProcess.respond (/node_modules/html-pdf-phantomjs-included/lib/pdf.js:134:17)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
    at Process.callbackTrampoline (internal/async_hooks.js:130:17)'
```

**Comment by tauksun** [comment]
Hi @ak-notify, which Operation System & Nodejs-version ?

**Comment by ak-notify** [comment]
Hi @tauksun I'm running it on Docker (image node: 14) linux, and Nodejs-version 14.19.x
